language: python
python:
  - "2.7"

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/d356e84a6850737ac196
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: python test/runner.py
